# Generated by Django 6.0.2 on 2026-02-17 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('expiry_date', models.DateField()),
                ('image', models.ImageField(upload_to='food_images/')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Accepted', 'Accepted'), ('Expired', 'Expired')], default='Available', max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
