# Generated by Django 6.0.2 on 2026-02-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fooddonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='shop_name',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
