# Generated by Django 6.0.2 on 2026-02-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fooddonation_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
