# Generated by Django 6.0.2 on 2026-03-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_fooddonation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddonation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
