# Generated by Django 6.0.2 on 2026-03-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_contactdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
