# Generated by Django 6.0.2 on 2026-03-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_pickuprequest_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
